version: '3'
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  auth: 
    build: ./Auth
    ports:
      - 8080:8080

  fetch: 
    build: ./Fetch
    ports:
      - 8081:8081

    depends_on:
      - redis
 